### ISSUE TITLE
Errors while running on Windows 7

### ISSUE THREAD

**Issue by mohsentaleb** [bogem/nehm#7]
Hi,
I get some errors at the end of each file download, but it's saved on disk anyway.
I'm running the following command in this path: C:\Users\Mohsen\Desktop\soundcloud
`$ nehm get 100`

and I get this log messages:

![nehm-windows](https://cloud.githubusercontent.com/assets/628654/21272532/ec5d9306-c3d4-11e6-8564-e06a8a3574e2.png)

**Comment by n10v** [comment]
Thanks for issue!

So many errors😰
It's very strange, what on Windows you have third error, because only on macOS tracks can't be added to iTunes.
Can you please send here, what did you entered (whole command, flags and etc.) to execute nehm.

Can you please send me links to these tracks?
I try to reproduce it on my computer

**Comment by mohsentaleb** [comment]
This is the exact command I ran:
`$ nehm get 100`
My profile name in soundcloud is `mohsentaleb`. The issue I'm having consists of two different problems:

1. When the name of the track which is being saved is in English, the track is saved on disk but an error message is logged on screen.
2. When the name of the track has utf-8 characters, the progress bar goes to 100% , an error is logged and the file is not saved on disk.

You can reproduce problem number 2 with this track: https://soundcloud.com/arsham_htn/cnmudbr0220i
and for problem  number 1: https://soundcloud.com/mahan-farzad/life-story

**Comment by mohsentaleb** [comment]
Another weird behavior with this track: https://soundcloud.com/cmdigital/dirk-maassen-solstice
Can't be saved at all.

**Comment by n10v** [comment]
Which error do you have?

**Comment by mohsentaleb** [comment]
I'm having both problem number 1 and 2 in https://github.com/bogem/nehm/issues/7#issuecomment-2676799999. The final error logs of my run is as below:
![untitled-2](https://cloud.githubusercontent.com/assets/628654/21276627/852c407a-c3e7-11e6-8a64-1b8bdc9aa01a.png)

**Comment by bogem** [comment]
Can you please send here, what did you entered (whole command, flags and etc.) to execute nehm?

**Comment by n10v** [comment]
#1 and #2 are not vaild issues, because at first `nehm` was written on ruby and these issues were because of ruby.

**Comment by mohsentaleb** [comment]
I think there was a mistyping with my comment and you were misdirected. Please read this comment again, I edited that: https://github.com/bogem/nehm/issues/7#issuecomment-267679999

**Comment by n10v** [comment]
Bugs with `exit status 23` are because of persian symbols, I think.

**Comment by n10v** [comment]
Yes, I didn't notice changes in your first comment.
First problem is because of the situation, what `nehm` successfully downloads track, but tries to add to iTunes (I don't know why, because `nehm` should add tracks to iTunes only on macOS. It's very strange). I can't reproduce it on my mac, because it works fine on it.
Second problem is because of maybe Windows` filesystem doesn't support unicode characters. I'll try to fix it. Also works fine on macOS

**Comment by bogem** [comment]
@mohsentaleb Can you please send here, what did you entered (e.g which flags did you use) to execute nehm?

**Comment by n10v** [comment]
Can you send me please, which config file do you have?
At least `itunesPlaylist` and `dlFolder` values

**Comment by mohsentaleb** [comment]
This is my `.nehmconfig` file:
>permalink: mohsentaleb
>dlFolder: ./
>itunesPlaylist: iPod

**Comment by n10v** [comment]
If you will delete third line, errors with `osascript` will be fixed.
Adding to iTunes is possible only on macOS.

**Comment by n10v** [comment]
Try to delete line with `dlFolder` in your config and try to execute nehm one more time.
Please send me screen of result then.

**Comment by n10v** [comment]
It's very hard to fix issues on Windows, because I haven't got any Windows machine.
And I don't want to buy Windows license. It's expensive for me only to test the `nehm` on it.

**Comment by mohsentaleb** [comment]
This is the log screen when I deleted the `dlFolder` and `itunesPlaylist` option in config file:
![untitled-5](https://cloud.githubusercontent.com/assets/628654/21278111/99203cb0-c3ee-11e6-91a2-b714cd3c217c.png)

**Comment by n10v** [comment]
I fixed some issues
Try to:
```bash
go get -u github.com/bogem/id3v2
go get -u github.com/bogem/nehm
go install github.com/bogem/nehm
```
Execute nehm and send the results please😊

**Comment by mohsentaleb** [comment]
Hi, Still getting errors with the new version.
![untitled](https://cloud.githubusercontent.com/assets/628654/21289291/58307ace-c4ae-11e6-837d-3e01e8073790.png)

**Comment by n10v** [comment]
Yes, because I didn't fix the bug when filename contains persian symbols.
I will fix it during the christmas holidays, hopefully.
